"""Aggiornamento del modello User: aggiunti family_expense_threshold e avatar

Revision ID: 00b095eb6f37
Revises: 514b232c1fe6
Create Date: 2025-02-11 20:00:03.301394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b095eb6f37'
down_revision = '514b232c1fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_expense_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('family_expense_threshold')

    # ### end Alembic commands ###
