"""Aggiunto plaid_access_token a Card

Revision ID: 514b232c1fe6
Revises: bfc7bcafc479
Create Date: 2025-02-11 18:20:28.262834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514b232c1fe6'
down_revision = 'bfc7bcafc479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_access_token', sa.String(length=500), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['external_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('plaid_access_token')

    # ### end Alembic commands ###
